"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var user_manager_config_1 = require("./user-manager.config");
exports.UserManagerConfig = user_manager_config_1.UserManagerConfig;
var user_manager_routes_1 = require("./user-manager.routes");
exports.UserManagerRoutes = user_manager_routes_1.UserManagerRoutes;
var index_component_1 = require("./index/index.component");
exports.UserManagerIndexComponent = index_component_1.UserManagerIndexComponent;
var user_manager_module_1 = require("./user-manager.module");
exports.UserManagerModule = user_manager_module_1.UserManagerModule;
