"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var resource_config_1 = require("./resource.config");
exports.FormioResourceConfig = resource_config_1.FormioResourceConfig;
var resources_service_1 = require("./resources.service");
exports.FormioResources = resources_service_1.FormioResources;
var resource_service_1 = require("./resource.service");
exports.FormioResourceService = resource_service_1.FormioResourceService;
var resource_component_1 = require("./resource.component");
exports.FormioResourceComponent = resource_component_1.FormioResourceComponent;
var view_component_1 = require("./view/view.component");
exports.FormioResourceViewComponent = view_component_1.FormioResourceViewComponent;
var edit_component_1 = require("./edit/edit.component");
exports.FormioResourceEditComponent = edit_component_1.FormioResourceEditComponent;
var delete_component_1 = require("./delete/delete.component");
exports.FormioResourceDeleteComponent = delete_component_1.FormioResourceDeleteComponent;
var create_component_1 = require("./create/create.component");
exports.FormioResourceCreateComponent = create_component_1.FormioResourceCreateComponent;
var index_component_1 = require("./index/index.component");
exports.FormioResourceIndexComponent = index_component_1.FormioResourceIndexComponent;
var resource_routes_1 = require("./resource.routes");
exports.FormioResourceRoutes = resource_routes_1.FormioResourceRoutes;
var resource_module_1 = require("./resource.module");
exports.FormioResource = resource_module_1.FormioResource;
